# Generated by Django 5.2.3 on 2025-06-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_us', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BodegaCentral',
            fields=[
                ('id_bdg', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_bdg', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'bodega_central',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estped', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'estado_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_hst', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'historial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_informe', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('modulo_origen', models.CharField(max_length=255, null=True)),
                ('contenido', models.CharField(max_length=255, null=True)),
                ('archivo_url', models.CharField(max_length=255, null=True)),
                ('fecha_generado', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'informe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_mprod', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_mprod', models.CharField(max_length=255)),
                ('descripcion_mprod', models.TextField()),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovInventario',
            fields=[
                ('id_mvin', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'mov_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_ntf', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_ntf', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_hora_ntd', models.DateTimeField()),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_p', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_entrega', models.DateTimeField()),
            ],
            options={
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalEntrega',
            fields=[
                ('id_psn', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_psn', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('patente', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'personal_entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prodc', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_prodc', models.CharField(max_length=255)),
                ('descripcion_prodc', models.CharField(max_length=255, null=True)),
                ('codigo_interno', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_provd', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres_provd', models.CharField(max_length=255)),
                ('direccion_provd', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('razon_social', models.CharField(max_length=255)),
                ('rut_empresa', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id_solc', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField()),
                ('observacion', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'solicitudes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=255, null=True)),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('rut', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
    ]
