# Generated by Django 5.2.3 on 2025-07-04 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_us', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('contrasena_old', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BodegaCentral',
            fields=[
                ('id_bdg', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_bdg', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'bodega_central',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id_estped', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'estado_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_hst', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'historial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_informe', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('modulo_origen', models.CharField(max_length=255, null=True)),
                ('contenido', models.TextField(null=True)),
                ('archivo_url', models.CharField(max_length=255, null=True)),
                ('fecha_generado', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'informe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_mprod', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_mprod', models.CharField(max_length=255)),
                ('descripcion_mprod', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'marca',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'modulos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovInventario',
            fields=[
                ('id_mvin', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'mov_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_ntf', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_ntf', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito')], default='info', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_hora_ntd', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_p', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_entrega', models.DateTimeField()),
            ],
            options={
                'db_table': 'pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'permisos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_prodc', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_prodc', models.CharField(max_length=255)),
                ('descripcion_prodc', models.CharField(max_length=255, null=True)),
                ('codigo_interno', models.CharField(max_length=255, unique=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_provd', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombres_provd', models.CharField(max_length=255)),
                ('direccion_provd', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('razon_social', models.CharField(max_length=255)),
                ('rut_empresa', models.DecimalField(decimal_places=0, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id_solc', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField()),
                ('estado', models.CharField(max_length=20, null=True)),
                ('despachada', models.BooleanField(null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solicitudes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudProductos',
            fields=[
                ('id_solc_prod', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'solicitud_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.BigAutoField(primary_key=True, serialize=False)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('stock_maximo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('bodega_fk', models.IntegerField(db_column='bodega_fk', null=True)),
                ('sucursal_fk', models.IntegerField(db_column='sucursal_fk', null=True)),
                ('proveedor_fk', models.IntegerField(db_column='proveedor_fk', null=True)),
            ],
            options={
                'db_table': 'stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=255, null=True)),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('descripcion', models.CharField(max_length=255, null=True)),
                ('rut', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalEntrega',
            fields=[
                ('id_psn', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_psn', models.CharField(max_length=255)),
                ('descripcion_psn', models.CharField(max_length=255)),
                ('patente', models.CharField(max_length=255)),
                ('usuario_fk', models.ForeignKey(db_column='usuario_fk', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal_entrega',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioNotificacion',
            fields=[
                ('id_ntf_us', models.AutoField(primary_key=True, serialize=False)),
                ('leida', models.BooleanField(default=False)),
                ('eliminada', models.BooleanField(default=False)),
                ('fecha_recibida', models.DateTimeField(auto_now_add=True)),
                ('notificacion', models.ForeignKey(db_column='id_ntf', on_delete=django.db.models.deletion.CASCADE, to='api.notificacion')),
                ('usuario', models.ForeignKey(db_column='id_us', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_notificacion',
            },
        ),
    ]
