# Generated by Django 5.2.3 on 2025-07-04 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarionotificacion',
            name='notificacion',
            field=models.ForeignKey(db_column='notificacion_id', on_delete=django.db.models.deletion.CASCADE, to='api.notificacion'),
        ),
        migrations.AlterField(
            model_name='usuarionotificacion',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
