# Generated by Django 5.2.3 on 2025-06-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudProductos',
            fields=[
                ('id_solc_prod', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'solicitud_productos',
                'managed': False,
            },
        ),
    ]
