# Generated by Django 5.2.3 on 2025-06-22 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_solicitudproductos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalentrega',
            options={'managed': True},
        ),
    ]
