# Generated by Django 5.2.3 on 2025-07-07 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sync_motivo_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado_anterior', models.ForeignKey(db_column='estado_anterior', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_estado_anterior', to='api.estadopedido')),
                ('estado_nuevo', models.ForeignKey(db_column='estado_nuevo', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estado_nuevo', to='api.estadopedido')),
                ('pedido_fk', models.ForeignKey(db_column='pedido_fk', on_delete=django.db.models.deletion.CASCADE, to='api.pedidos')),
                ('usuario_fk', models.ForeignKey(db_column='usuario_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_estado_pedido',
                'managed': True,
            },
        ),
    ]
