# Generated by Django 5.2.3 on 2025-06-22 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_personalentrega_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalentrega',
            name='usuario_fk',
            field=models.ForeignKey(db_column='usuario_fk', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
