# Generated by Django 5.2.3 on 2025-07-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_historialestadopedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialestadopedido',
            old_name='id',
            new_name='id_hist_ped',
        ),
    ]
