# Generated by Django 5.2.3 on 2025-07-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_id_historialestadopedido_id_hist_ped'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidos',
            options={'managed': True},
        ),
    ]
